version: '3.8'
services:
  alertservice:
    build:
      context: ./alertservice
    ports:
      - "8080:8080"
    networks:
      - monitor-net

  simulador:
    build:
      context: ./simulador
    depends_on:
      - alertservice
    networks:
      - monitor-net

networks:
  monitor-net:

