version: '3.9'

services:
  alertservice:
    build: ./alertservice
    container_name: alertservice
    ports:
      - "8080:8080"
    networks:
      - monitor-net

  simulador:
    build: ./simulador
    container_name: simulador
    depends_on:
      - alertservice
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge

