version: "3.8"

services:
  sensor_service:
    build: ./sensor_service
    depends_on:
      - collector_service

  collector_service:
    build: ./collector_service
    ports:
      - "5010:5010"
    depends_on:
      - storage_service
      - alert_services

  storage_service:
    build: ./storage_service
    ports:
      - "5011:5011"

  alert_services:
    build: ./alert_services
    ports:
      - "5012:5012"

